# Generated by Django 3.1.1 on 2020-11-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll_id',
            field=models.IntegerField(verbose_name='所屬投票主題編號'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='選項標題'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(verbose_name='投票內容說明'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='投票主題'),
        ),
    ]
